from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ElevatorViewSet, FloorViewSet, UserRequestViewSet, initialize_elevator_system_view

router = DefaultRouter()
router.register(r'elevators', ElevatorViewSet, basename='elevators')
router.register(r'floors', FloorViewSet, basename='floors')
router.register(r'user-requests', UserRequestViewSet, basename='user-requests')

urlpatterns = [
    # Include the URL patterns generated by the router
    path('', include(router.urls)),

    # Add the 'initialize_elevator_system_view' for the 'initialize_elevator_system' endpoint
    path('api/elevators/initialize_elevator_system/', initialize_elevator_system_view, name='initialize_elevator_system'),
]
